### ISSUE TITLE
Fatal error during ansible provision

### ISSUE THREAD

**Issue by Petr2016** [hoelsner/product-database#2]
Hello Henry,

I meet with unexpected error during delpoy productdb onto Ubuntu 16.04 server. During VM boot and excution of provison script I recieve next message on step:

TASK [copy source directory from local directory] ******************************
fatal: [productdb]: FAILED! => {"changed": true, "cmd": ["cp", "-rfu", "/vagrant/.", "/var/www/productdb/source"], "delta": "0:00:00.006270", "end": "2016-06-28 11:47:52.468539", "failed": true, "rc": 1, "start": "2016-06-28 11:47:52.462269", "stderr": "cp: cannot stat '/vagrant/.': No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}

Could you please recommend to me steps how to solve this isse.

WBR
Petr

**Comment by hoelsner** [comment]
Hi Petr, 

when deploying the product database on a server (not a Vagrant VM), you need to clone the source directly from GitHub. You find the following two variables in the **stage_machine.yaml**: 
- `system_source` that controls where the code is located (must be `git` in your case)
- `site_source_branch` that controls the git version (use `master`, that is the latest branch)

I see in the output that the playbook try to copy the source files from the local path `/vagrant`, which is not available if you deploy it on a dedicated VM. Can you please check the value of the two variables in your **stage_machine.yaml**?

Best regards, Henry

**Comment by Petr2016** [comment]
Hi Henry,

I think we meet with a little bit misunderstanding. I'm deploy ansible and vagrant onto one VM (Ubunut 16.04 server), which i'm deploy into ESXi hypervisor. This VM as host role, deploy into vbox environment productdb with using also Ubuntu 16.04 ) 
But I goes by another way and setup Desktop Ubuntu 16.04 instead Server version, and all working properly. I can't say that I find solution to this error. But my problem is solved )

From your agreement I would like to close this issue.

WBR
Petr

**Comment by hoelsner** [comment]
Hi Petr, 

okay. As far as I understand, you deploy an Ubuntu Desktop on an ESXi server and the Ubuntu Desktop uses Vagrant/VirtualBox to create an additional VM to run the Product Database. Because of the dual virtualization layer, I recommend to install the Ubuntu Server that runs the Product Database directly on your ESXi server. 

Today, I added a local deployment script to the repository that don't require two devices for the deployment, instead it uses Ansible on localhost (I planned to add/test this for quite some time). You can now install it directly on Ubuntu 16.04 without any additional machine. If you're interested, take a look at the [README.md](https://github.com/hoelsner/product-database#dedicated-server-setup) file. 

Best regards, Henry

**Comment by Petr2016** [comment]
Hi Henry! 

Great news, I try to test this deployment and report if find out any issues ) 
I very often meet with some strange issues ))

Thank you for your great work!

WBR
Petr

**Comment by lukezzz** [comment]
Hi Petr,

Tried the local deployment but failed, I think the username and password should be correct. So why the script said the authentication failure?

PLAY [staging] *****************************************************************

TASK [setup] *******************************************************************
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Authentication failure.", "unreachable": true}
	to retry, use: --limit @/home/systemadmin/eox/product-database/deploy/stage_default/stage-machine.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0   

Regards,
Luke

**Comment by Petr2016** [comment]
Hi Lukezzz,

Try to do apt-get update, apt-get upgrade. 
Another things: when you use command invoke deploy_local -u <username> -p <password> - do you use system username\password combination or random new?
I use username\password which I use to get access to system, it is important that user which you use to local deploy have access through ssh to system.

Lukezz why do you not use just vagrant VM local deployment - it's more easy insted deploy through Ansible.  You just get vagrant and after this spell one command : vagrant up productdb (in product db directory) and after it succefully load you can get access to ProductDb trough localhost:16000

WBR
Petr

**Comment by hoelsner** [comment]
Hi Lukezzz, 

please check that the server is reachable through SSH. The installation scripts are always based on the Ansible playbook and Ansible will try to establish an SSH connection to the localhost to execute the playbook. I think this is not possible in your case because of the unreachable state for the 127.0.0.1.

Please let us know if this works for you.

Kind regards, 
Henry

**Comment by lukezzz** [comment]
Thanks guys, i will try the vagrant.

**Comment by edurguti** [comment]
Im getting the following when using vagrant.

==> productdb: Reading state information...
==> productdb: python is already the newest version (2.7.11-1).
==> productdb: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> productdb: Running provisioner: ansible...
    productdb: Running ansible-playbook...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your host system.

If you haven't installed Ansible yet, please install Ansible
on your host system. Vagrant can't do this for you in a safe and
automated way.
Please check https://docs.ansible.com for more information.

**Comment by hoelsner** [comment]
Already answered in #4
